In [1]:
import numpy as np
import pandas as pd

In [76]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error

In [48]:
df_janvier = pd.read_parquet("yellow_tripdata_2021-01.parquet")
df_janvier

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1.0,2.10,1.0,N,142,43,2,8.00,3.00,0.5,0.00,0.00,0.3,11.80,2.5,NaN
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1.0,0.20,1.0,N,238,151,2,3.00,0.50,0.5,0.00,0.00,0.3,4.30,0.0,NaN
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1.0,14.70,1.0,N,132,165,1,42.00,0.50,0.5,8.65,0.00,0.3,51.95,0.0,NaN
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0.0,10.60,1.0,N,138,132,1,29.00,0.50,0.5,6.05,0.00,0.3,36.35,0.0,NaN
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1.0,4.94,1.0,N,68,33,1,16.50,0.50,0.5,4.06,0.00,0.3,24.36,2.5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1369764,2,2021-01-31 23:03:00,2021-01-31 23:33:00,NaN,8.89,NaN,NaN,229,181,0,27.78,0.00,0.5,7.46,0.00,0.3,38.54,NaN,NaN
1369765,2,2021-01-31 23:29:00,2021-01-31 23:51:00,NaN,7.43,NaN,NaN,41,70,0,32.58,0.00,0.5,0.00,6.12,0.3,39.50,NaN,NaN
1369766,2,2021-01-31 23:25:00,2021-01-31 23:38:00,NaN,6.26,NaN,NaN,74,137,0,16.85,0.00,0.5,3.90,0.00,0.3,24.05,NaN,NaN
1369767,6,2021-01-31 23:01:06,2021-02-01 00:02:03,NaN,19.70,NaN,NaN,265,188,0,53.68,0.00,0.5,0.00,0.00,0.3,54.48,NaN,NaN
1369768,2,2021-01-31 23:08:29,2021-01-31 23:31:22,NaN,4.68,NaN,NaN,89,61,0,25.45,2.75,0.5,0.00,0.00,0.3,29.00,NaN,NaN

In [49]:
df_fevrier = pd.read_parquet("yellow_tripdata_2021-02.parquet")
df_fevrier

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,1,2021-02-01 00:40:47,2021-02-01 00:48:28,1.0,2.30,1.0,N,141,226,2,8.50,3.00,0.5,0.00,0.0,0.3,12.30,2.5,NaN
1,1,2021-02-01 00:07:44,2021-02-01 00:20:31,1.0,1.60,1.0,N,43,263,2,9.50,3.00,0.5,0.00,0.0,0.3,13.30,0.0,NaN
2,1,2021-02-01 00:59:36,2021-02-01 01:24:13,1.0,5.30,1.0,N,114,263,2,19.00,3.00,0.5,0.00,0.0,0.3,22.80,2.5,NaN
3,2,2021-02-01 00:03:26,2021-02-01 00:16:32,1.0,2.79,1.0,N,236,229,1,11.00,0.50,0.5,2.96,0.0,0.3,17.76,2.5,NaN
4,2,2021-02-01 00:20:20,2021-02-01 00:24:03,2.0,0.64,1.0,N,229,140,1,4.50,0.50,0.5,1.66,0.0,0.3,9.96,2.5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1371704,6,2021-02-28 23:02:08,2021-02-28 23:02:02,NaN,16.09,NaN,NaN,265,3,0,42.55,0.00,0.5,0.00,0.0,0.3,43.35,NaN,NaN
1371705,2,2021-02-28 23:27:00,2021-02-28 23:41:00,NaN,4.42,NaN,NaN,68,24,0,17.14,0.00,0.5,4.33,0.0,0.3,24.77,NaN,NaN
1371706,2,2021-02-28 23:18:05,2021-02-28 23:26:48,NaN,1.50,NaN,NaN,68,137,0,9.46,0.00,0.5,2.64,0.0,0.3,15.40,NaN,NaN
1371707,2,2021-02-28 23:41:07,2021-03-01 00:13:44,NaN,15.30,NaN,NaN,113,254,0,59.15,2.75,0.5,0.00,0.0,0.3,62.70,NaN,NaN
1371708,2,2021-02-28 23:04:15,2021-02-28 23:33:17,NaN,12.73,NaN,NaN,226,10,0,44.62,2.75,0.5,0.00,0.0,0.3,48.17,NaN,NaN

In [50]:
# question 1
nb_colonne = len(df_janvier.columns)
nb_colonne

19

In [51]:
df_janvier['duration'] = (df_janvier['tpep_dropoff_datetime'] - df_janvier['tpep_pickup_datetime']).dt.total_seconds() / 60
df_fevrier['duration'] = (df_fevrier['tpep_dropoff_datetime'] - df_fevrier['tpep_pickup_datetime']).dt.total_seconds() / 60

In [52]:
# question 2 
std_val = df_janvier['duration'].std()
std_val

np.float64(131.20060819433766)

In [53]:
nb_record_before = len(df_janvier)

df_janvier = df_janvier[(df_janvier['duration'] >= 1) & (df_janvier['duration'] <=60)]
df_fevrier = df_fevrier[(df_fevrier['duration'] >= 1) & (df_fevrier['duration'] <=60)]

nb_record_after = len(df_janvier)

In [54]:
# question 3 
nb_removed = (nb_record_after / nb_record_before)*100
nb_removed

98.06427215099772

In [62]:
categorical  = ['PULocationID', 'DOLocationID']

df_janvier[categorical] = df_janvier[categorical].astype(str)
dict_janvier = df_janvier[categorical].to_dict(orient='records')
dict_janvier

[{'PULocationID': '142', 'DOLocationID': '43'},
 {'PULocationID': '132', 'DOLocationID': '165'},
 {'PULocationID': '138', 'DOLocationID': '132'},
 {'PULocationID': '68', 'DOLocationID': '33'},
 {'PULocationID': '224', 'DOLocationID': '68'},
 {'PULocationID': '95', 'DOLocationID': '157'},
 {'PULocationID': '90', 'DOLocationID': '40'},
 {'PULocationID': '97', 'DOLocationID': '129'},
 {'PULocationID': '263', 'DOLocationID': '142'},
 {'PULocationID': '164', 'DOLocationID': '255'},
 {'PULocationID': '255', 'DOLocationID': '80'},
 {'PULocationID': '138', 'DOLocationID': '166'},
 {'PULocationID': '142', 'DOLocationID': '50'},
 {'PULocationID': '50', 'DOLocationID': '142'},
 {'PULocationID': '236', 'DOLocationID': '237'},
 {'PULocationID': '142', 'DOLocationID': '239'},
 {'PULocationID': '238', 'DOLocationID': '166'},
 {'PULocationID': '239', 'DOLocationID': '238'},
 {'PULocationID': '151', 'DOLocationID': '142'},
 {'PULocationID': '239', 'DOLocationID': '142'},
 {'PULocationID': '238', 'DOLocationID': '142'},
 {'PULocationID': '249', 'DOLocationID': '137'},
 {'PULocationID': '107', 'DOLocationID': '163'},
 {'PULocationID': '132', 'DOLocationID': '3'},
 {'PULocationID': '48', 'DOLocationID': '226'},
 {'PULocationID': '238', 'DOLocationID': '162'},
 {'PULocationID': '4', 'DOLocationID': '43'},
 {'PULocationID': '48', 'DOLocationID': '41'},
 {'PULocationID': '132', 'DOLocationID': '226'},
 {'PULocationID': '229', 'DOLocationID': '151'},
 {'PULocationID': '238', 'DOLocationID': '166'},
 {'PULocationID': '151', 'DOLocationID': '238'},
 {'PULocationID': '138', 'DOLocationID': '82'},
 {'PULocationID': '264', 'DOLocationID': '231'},
 {'PULocationID': '263', 'DOLocationID': '142'},
 {'PULocationID': '48', 'DOLocationID': '32'},
 {'PULocationID': '151', 'DOLocationID': '90'},
 {'PULocationID': '238', 'DOLocationID': '42'},
 {'PULocationID': '137', 'DOLocationID': '140'},
 {'PULocationID': '114', 'DOLocationID': '234'},
 {'PULocationID': '100', 'DOLocationID': '229'},
 {'PULocationID': '229', 'DOLocationID': '170'},
 {'PULocationID': '48', 'DOLocationID': '239'},
 {'PULocationID': '142', 'DOLocationID': '48'},
 {'PULocationID': '137', 'DOLocationID': '256'},
 {'PULocationID': '140', 'DOLocationID': '262'},
 {'PULocationID': '264', 'DOLocationID': '238'},
 {'PULocationID': '170', 'DOLocationID': '114'},
 {'PULocationID': '186', 'DOLocationID': '87'},
 {'PULocationID': '209', 'DOLocationID': '256'},
 {'PULocationID': '132', 'DOLocationID': '107'},
 {'PULocationID': '232', 'DOLocationID': '112'},
 {'PULocationID': '164', 'DOLocationID': '141'},
 {'PULocationID': '141', 'DOLocationID': '236'},
 {'PULocationID': '263', 'DOLocationID': '236'},
 {'PULocationID': '141', 'DOLocationID': '236'},
 {'PULocationID': '141', 'DOLocationID': '140'},
 {'PULocationID': '263', 'DOLocationID': '75'},
 {'PULocationID': '249', 'DOLocationID': '238'},
 {'PULocationID': '229', 'DOLocationID': '229'},
 {'PULocationID': '249', 'DOLocationID': '229'},
 {'PULocationID': '164', 'DOLocationID': '87'},
 {'PULocationID': '132', 'DOLocationID': '229'},
 {'PULocationID': '113', 'DOLocationID': '87'},
 {'PULocationID': '261', 'DOLocationID': '48'},
 {'PULocationID': '125', 'DOLocationID': '48'},
 {'PULocationID': '48', 'DOLocationID': '143'},
 {'PULocationID': '186', 'DOLocationID': '231'},
 {'PULocationID': '246', 'DOLocationID': '24'},
 {'PULocationID': '158', 'DOLocationID': '211'},
 {'PULocationID': '170', 'DOLocationID': '249'},
 {'PULocationID': '237', 'DOLocationID': '236'},
 {'PULocationID': '141', 'DOLocationID': '248'},
 {'PULocationID': '75', 'DOLocationID': '263'},
 {'PULocationID': '263', 'DOLocationID': '141'},
 {'PULocationID': '162', 'DOLocationID': '75'},
 {'PULocationID': '263', 'DOLocationID': '233'},
 {'PULocationID': '141', 'DOLocationID': '263'},
 {'PULocationID': '263', 'DOLocationID': '141'},
 {'PULocationID': '262', 'DOLocationID': '142'},
 {'PULocationID': '137', 'DOLocationID': '263'},
 {'PULocationID': '140', 'DOLocationID': '229'},
 {'PULocationID': '140', 'DOLocationID': '113'},
 {'PULocationID': '140', 'DOLocationID': '238'},
 {'PULocationID': '239', 'DOLocationID': '151'},
 {'PULocationID': '75', 'DOLocationID': '264'},
 {'PULocationID': '90', 'DOLocationID': '142'},
 {'PULocationID': '48', 'DOLocationID': '142'},
 {'PULocationID': '137', 'DOLocationID': '232'},
 {'PULocationID': '79', 'DOLocationID': '45'},
 {'PULocationID': '224', 'DOLocationID': '75'},
 {'PULocationID': '236', 'DOLocationID': '75'},
 {'PULocationID': '140', 'DOLocationID': '142'},
 {'PULocationID': '161', 'DOLocationID': '226'},
 {'PULocationID': '162', 'DOLocationID': '74'},
 {'PULocationID': '144', 'DOLocationID': '170'},
 {'PULocationID': '264', 'DOLocationID': '264'},
 {'PULocationID': '229', 'DOLocationID': '237'},
 {'PULocationID': '75', 'DOLocationID': '151'},
 {'PULocationID': '238', 'DOLocationID': '236'},
 {'PULocationID': '132', 'DOLocationID': '219'},
 {'PULocationID': '79', 'DOLocationID': '41'},
 {'PULocationID': '238', 'DOLocationID': '239'},
 {'PULocationID': '142', 'DOLocationID': '238'},
 {'PULocationID': '137', 'DOLocationID': '43'},
 {'PULocationID': '137', 'DOLocationID': '229'},
 {'PULocationID': '234', 'DOLocationID': '234'},
 {'PULocationID': '236', 'DOLocationID': '140'},
 {'PULocationID': '140', 'DOLocationID': '43'},
 {'PULocationID': '239', 'DOLocationID': '238'},
 {'PULocationID': '263', 'DOLocationID': '236'},
 {'PULocationID': '236', 'DOLocationID': '238'},
 {'PULocationID': '231', 'DOLocationID': '137'},
 {'PULocationID': '68', 'DOLocationID': '50'},
 {'PULocationID': '249', 'DOLocationID': '181'},
 {'PULocationID': '236', 'DOLocationID': '237'},
 {'PULocationID': '230', 'DOLocationID': '82'},
 {'PULocationID': '114', 'DOLocationID': '234'},
 {'PULocationID': '48', 'DOLocationID': '100'},
 {'PULocationID': '79', 'DOLocationID': '7'},
 {'PULocationID': '264', 'DOLocationID': '130'},
 {'PULocationID': '90', 'DOLocationID': '238'},
 {'PULocationID': '43', 'DOLocationID': '127'},
 {'PULocationID': '233', 'DOLocationID': '107'},
 {'PULocationID': '229', 'DOLocationID': '140'},
 {'PULocationID': '140', 'DOLocationID': '229'},
 {'PULocationID': '68', 'DOLocationID': '74'},
 {'PULocationID': '74', 'DOLocationID': '41'},
 {'PULocationID': '48', 'DOLocationID': '226'},
 {'PULocationID': '263', 'DOLocationID': '41'},
 {'PULocationID': '263', 'DOLocationID': '140'},
 {'PULocationID': '236', 'DOLocationID': '262'},
 {'PULocationID': '262', 'DOLocationID': '263'},
 {'PULocationID': '237', 'DOLocationID': '237'},
 {'PULocationID': '164', 'DOLocationID': '227'},
 {'PULocationID': '234', 'DOLocationID': '116'},
 {'PULocationID': '113', 'DOLocationID': '162'},
 {'PULocationID': '237', 'DOLocationID': '262'},
 {'PULocationID': '164', 'DOLocationID': '137'},
 {'PULocationID': '249', 'DOLocationID': '224'},
 {'PULocationID': '229', 'DOLocationID': '229'},
 {'PULocationID': '141', 'DOLocationID': '234'},
 {'PULocationID': '161', 'DOLocationID': '170'},
 {'PULocationID': '113', 'DOLocationID': '65'},
 {'PULocationID': '48', 'DOLocationID': '41'},
 {'PULocationID': '161', 'DOLocationID': '48'},
 {'PULocationID': '113', 'DOLocationID': '236'},
 {'PULocationID': '113', 'DOLocationID': '36'},
 {'PULocationID': '132', 'DOLocationID': '197'},
 {'PULocationID': '236', 'DOLocationID': '28'},
 {'PULocationID': '141', 'DOLocationID': '236'},
 {'PULocationID': '161', 'DOLocationID': '229'},
 {'PULocationID': '143', 'DOLocationID': '41'},
 {'PULocationID': '70', 'DOLocationID': '265'},
 {'PULocationID': '100', 'DOLocationID': '231'},
 {'PULocationID': '249', 'DOLocationID': '233'},
 {'PULocationID': '237', 'DOLocationID': '141'},
 {'PULocationID': '142', 'DOLocationID': '229'},
 {'PULocationID': '229', 'DOLocationID': '137'},
 {'PULocationID': '79', 'DOLocationID': '144'},
 {'PULocationID': '100', 'DOLocationID': '230'},
 {'PULocationID': '186', 'DOLocationID': '79'},
 {'PULocationID': '107', 'DOLocationID': '162'},
 {'PULocationID': '90', 'DOLocationID': '90'},
 {'PULocationID': '48', 'DOLocationID': '164'},
 {'PULocationID': '162', 'DOLocationID': '237'},
 {'PULocationID': '234', 'DOLocationID': '249'},
 {'PULocationID': '234', 'DOLocationID': '239'},
 {'PULocationID': '90', 'DOLocationID': '133'},
 {'PULocationID': '229', 'DOLocationID': '236'},
 {'PULocationID': '137', 'DOLocationID': '79'},
 {'PULocationID': '107', 'DOLocationID': '229'},
 {'PULocationID': '236', 'DOLocationID': '141'},
 {'PULocationID': '237', 'DOLocationID': '75'},
 {'PULocationID': '141', 'DOLocationID': '79'},
 {'PULocationID': '48', 'DOLocationID': '68'},
 {'PULocationID': '142', 'DOLocationID': '263'},
 {'PULocationID': '236', 'DOLocationID': '237'},
 {'PULocationID': '143', 'DOLocationID': '158'},
 {'PULocationID': '142', 'DOLocationID': '116'},
 {'PULocationID': '107', 'DOLocationID': '256'},
 {'PULocationID': '137', 'DOLocationID': '49'},
 {'PULocationID': '234', 'DOLocationID': '237'},
 {'PULocationID': '68', 'DOLocationID': '170'},
 {'PULocationID': '166', 'DOLocationID': '75'},
 {'PULocationID': '151', 'DOLocationID': '74'},
 {'PULocationID': '237', 'DOLocationID': '163'},
 {'PULocationID': '238', 'DOLocationID': '263'},
 {'PULocationID': '13', 'DOLocationID': '233'},
 {'PULocationID': '231', 'DOLocationID': '151'},
 {'PULocationID': '249', 'DOLocationID': '142'},
 {'PULocationID': '239', 'DOLocationID': '229'},
 {'PULocationID': '48', 'DOLocationID': '195'},
 {'PULocationID': '142', 'DOLocationID': '75'},
 {'PULocationID': '230', 'DOLocationID': '145'},
 {'PULocationID': '239', 'DOLocationID': '48'},
 {'PULocationID': '48', 'DOLocationID': '107'},
 {'PULocationID': '107', 'DOLocationID': '107'},
 {'PULocationID': '161', 'DOLocationID': '164'},
 {'PULocationID': '113', 'DOLocationID': '228'},
 {'PULocationID': '229', 'DOLocationID': '236'},
 {'PULocationID': '237', 'DOLocationID': '236'},
 {'PULocationID': '75', 'DOLocationID': '263'},
 {'PULocationID': '229', 'DOLocationID': '140'},
 {'PULocationID': '140', 'DOLocationID': '236'},
 {'PULocationID': '43', 'DOLocationID': '41'},
 {'PULocationID': '43', 'DOLocationID': '107'},
 {'PULocationID': '230', 'DOLocationID': '137'},
 {'PULocationID': '237', 'DOLocationID': '229'},
 {'PULocationID': '262', 'DOLocationID': '236'},
 {'PULocationID': '236', 'DOLocationID': '107'},
 {'PULocationID': '237', 'DOLocationID': '162'},
 {'PULocationID': '68', 'DOLocationID': '151'},
 {'PULocationID': '238', 'DOLocationID': '161'},
 {'PULocationID': '68', 'DOLocationID': '262'},
 {'PULocationID': '100', 'DOLocationID': '13'},
 {'PULocationID': '68', 'DOLocationID': '239'},
 {'PULocationID': '236', 'DOLocationID': '141'},
 {'PULocationID': '161', 'DOLocationID': '161'},
 {'PULocationID': '7', 'DOLocationID': '61'},
 {'PULocationID': '233', 'DOLocationID': '140'},
 {'PULocationID': '262', 'DOLocationID': '202'},
 {'PULocationID': '230', 'DOLocationID': '181'},
 {'PULocationID': '249', 'DOLocationID': '41'},
 {'PULocationID': '48', 'DOLocationID': '142'},
 {'PULocationID': '264', 'DOLocationID': '165'},
 {'PULocationID': '113', 'DOLocationID': '75'},
 {'PULocationID': '164', 'DOLocationID': '170'},
 {'PULocationID': '48', 'DOLocationID': '233'},
 {'PULocationID': '141', 'DOLocationID': '236'},
 {'PULocationID': '239', 'DOLocationID': '151'},
 {'PULocationID': '166', 'DOLocationID': '41'},
 {'PULocationID': '43', 'DOLocationID': '211'},
 {'PULocationID': '113', 'DOLocationID': '79'},
 {'PULocationID': '142', 'DOLocationID': '236'},
 {'PULocationID': '263', 'DOLocationID': '263'},
 {'PULocationID': '263', 'DOLocationID': '107'},
 {'PULocationID': '107', 'DOLocationID': '88'},
 {'PULocationID': '107', 'DOLocationID': '162'},
 {'PULocationID': '141', 'DOLocationID': '163'},
 {'PULocationID': '137', 'DOLocationID': '66'},
 {'PULocationID': '239', 'DOLocationID': '166'},
 {'PULocationID': '151', 'DOLocationID': '41'},
 {'PULocationID': '238', 'DOLocationID': '4'},
 {'PULocationID': '114', 'DOLocationID': '249'},
 {'PULocationID': '144', 'DOLocationID': '143'},
 {'PULocationID': '170', 'DOLocationID': '239'},
 {'PULocationID': '90', 'DOLocationID': '164'},
 {'PULocationID': '161', 'DOLocationID': '244'},
 {'PULocationID': '48', 'DOLocationID': '68'},
 {'PULocationID': '238', 'DOLocationID': '239'},
 {'PULocationID': '263', 'DOLocationID': '141'},
 {'PULocationID': '100', 'DOLocationID': '233'},
 {'PULocationID': '43', 'DOLocationID': '75'},
 {'PULocationID': '141', 'DOLocationID': '142'},
 {'PULocationID': '142', 'DOLocationID': '141'},
 {'PULocationID': '164', 'DOLocationID': '164'},
 {'PULocationID': '162', 'DOLocationID': '162'},
 {'PULocationID': '142', 'DOLocationID': '237'},
 {'PULocationID': '137', 'DOLocationID': '61'},
 {'PULocationID': '137', 'DOLocationID': '159'},
 {'PULocationID': '45', 'DOLocationID': '61'},
 {'PULocationID': '107', 'DOLocationID': '137'},
 {'PULocationID': '229', 'DOLocationID': '229'},
 {'PULocationID': '163', 'DOLocationID': '229'},
 {'PULocationID': '263', 'DOLocationID': '237'},
 {'PULocationID': '140', 'DOLocationID': '140'},
 {'PULocationID': '262', 'DOLocationID': '229'},
 {'PULocationID': '229', 'DOLocationID': '161'},
 {'PULocationID': '142', 'DOLocationID': '141'},
 {'PULocationID': '132', 'DOLocationID': '181'},
 {'PULocationID': '114', 'DOLocationID': '143'},
 {'PULocationID': '151', 'DOLocationID': '75'},
 {'PULocationID': '249', 'DOLocationID': '179'},
 {'PULocationID': '162', 'DOLocationID': '43'},
 {'PULocationID': '238', 'DOLocationID': '230'},
 {'PULocationID': '75', 'DOLocationID': '233'},
 {'PULocationID': '246', 'DOLocationID': '158'},
 {'PULocationID': '68', 'DOLocationID': '68'},
 {'PULocationID': '68', 'DOLocationID': '116'},
 {'PULocationID': '166', 'DOLocationID': '239'},
 {'PULocationID': '161', 'DOLocationID': '107'},
 {'PULocationID': '75', 'DOLocationID': '151'},
 {'PULocationID': '43', 'DOLocationID': '41'},
 {'PULocationID': '230', 'DOLocationID': '233'},
 {'PULocationID': '137', 'DOLocationID': '260'},
 {'PULocationID': '132', 'DOLocationID': '21'},
 {'PULocationID': '170', 'DOLocationID': '262'},
 {'PULocationID': '161', 'DOLocationID': '4'},
 {'PULocationID': '79', 'DOLocationID': '236'},
 {'PULocationID': '43', 'DOLocationID': '142'},
 {'PULocationID': '230', 'DOLocationID': '142'},
 {'PULocationID': '91', 'DOLocationID': '240'},
 {'PULocationID': '161', 'DOLocationID': '145'},
 {'PULocationID': '246', 'DOLocationID': '48'},
 {'PULocationID': '48', 'DOLocationID': '79'},
 {'PULocationID': '90', 'DOLocationID': '263'},
 {'PULocationID': '263', 'DOLocationID': '263'},
 {'PULocationID': '78', 'DOLocationID': '47'},
 {'PULocationID': '148', 'DOLocationID': '232'},
 {'PULocationID': '107', 'DOLocationID': '97'},
 {'PULocationID': '97', 'DOLocationID': '263'},
 {'PULocationID': '164', 'DOLocationID': '140'},
 {'PULocationID': '79', 'DOLocationID': '137'},
 {'PULocationID': '230', 'DOLocationID': '262'},
 {'PULocationID': '90', 'DOLocationID': '68'},
 {'PULocationID': '249', 'DOLocationID': '148'},
 {'PULocationID': '148', 'DOLocationID': '114'},
 {'PULocationID': '100', 'DOLocationID': '130'},
 {'PULocationID': '211', 'DOLocationID': '211'},
 {'PULocationID': '234', 'DOLocationID': '79'},
 {'PULocationID': '234', 'DOLocationID': '237'},
 {'PULocationID': '113', 'DOLocationID': '79'},
 {'PULocationID': '170', 'DOLocationID': '141'},
 {'PULocationID': '138', 'DOLocationID': '90'},
 {'PULocationID': '234', 'DOLocationID': '211'},
 {'PULocationID': '141', 'DOLocationID': '262'},
 {'PULocationID': '132', 'DOLocationID': '255'},
 {'PULocationID': '163', 'DOLocationID': '141'},
 {'PULocationID': '164', 'DOLocationID': '75'},
 {'PULocationID': '264', 'DOLocationID': '264'},
 {'PULocationID': '264', 'DOLocationID': '264'},
 {'PULocationID': '264', 'DOLocationID': '264'},
 {'PULocationID': '170', 'DOLocationID': '229'},
 {'PULocationID': '140', 'DOLocationID': '262'},
 {'PULocationID': '262', 'DOLocationID': '87'},
 {'PULocationID': '107', 'DOLocationID': '68'},
 {'PULocationID': '48', 'DOLocationID': '24'},
 {'PULocationID': '151', 'DOLocationID': '166'},
 {'PULocationID': '166', 'DOLocationID': '166'},
 {'PULocationID': '238', 'DOLocationID': '262'},
 {'PULocationID': '141', 'DOLocationID': '169'},
 {'PULocationID': '233', 'DOLocationID': '198'},
 {'PULocationID': '237', 'DOLocationID': '24'},
 {'PULocationID': '234', 'DOLocationID': '230'},
 {'PULocationID': '186', 'DOLocationID': '186'},
 {'PULocationID': '68', 'DOLocationID': '186'},
 {'PULocationID': '186', 'DOLocationID': '233'},
 {'PULocationID': '151', 'DOLocationID': '236'},
 {'PULocationID': '263', 'DOLocationID': '238'},
 {'PULocationID': '132', 'DOLocationID': '35'},
 {'PULocationID': '74', 'DOLocationID': '74'},
 {'PULocationID': '230', 'DOLocationID': '234'},
 {'PULocationID': '100', 'DOLocationID': '261'},
 {'PULocationID': '137', 'DOLocationID': '33'},
 {'PULocationID': '48', 'DOLocationID': '144'},
 {'PULocationID': '114', 'DOLocationID': '68'},
 {'PULocationID': '79', 'DOLocationID': '203'},
 {'PULocationID': '107', 'DOLocationID': '137'},
 {'PULocationID': '170', 'DOLocationID': '141'},
 {'PULocationID': '141', 'DOLocationID': '48'},
 {'PULocationID': '142', 'DOLocationID': '57'},
 {'PULocationID': '48', 'DOLocationID': '90'},
 {'PULocationID': '48', 'DOLocationID': '90'},
 {'PULocationID': '107', 'DOLocationID': '224'},
 {'PULocationID': '161', 'DOLocationID': '209'},
 {'PULocationID': '231', 'DOLocationID': '262'},
 {'PULocationID': '143', 'DOLocationID': '48'},
 {'PULocationID': '143', 'DOLocationID': '170'},
 {'PULocationID': '263', 'DOLocationID': '141'},
 {'PULocationID': '237', 'DOLocationID': '262'},
 {'PULocationID': '263', 'DOLocationID': '237'},
 {'PULocationID': '141', 'DOLocationID': '112'},
 {'PULocationID': '48', 'DOLocationID': '88'},
 {'PULocationID': '209', 'DOLocationID': '166'},
 {'PULocationID': '87', 'DOLocationID': '141'},
 {'PULocationID': '161', 'DOLocationID': '48'},
 {'PULocationID': '138', 'DOLocationID': '75'},
 {'PULocationID': '237', 'DOLocationID': '107'},
 {'PULocationID': '114', 'DOLocationID': '234'},
 {'PULocationID': '234', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '48'},
 {'PULocationID': '229', 'DOLocationID': '142'},
 {'PULocationID': '237', 'DOLocationID': '43'},
 {'PULocationID': '43', 'DOLocationID': '143'},
 {'PULocationID': '161', 'DOLocationID': '262'},
 {'PULocationID': '141', 'DOLocationID': '43'},
 {'PULocationID': '100', 'DOLocationID': '229'},
 {'PULocationID': '263', 'DOLocationID': '142'},
 {'PULocationID': '142', 'DOLocationID': '163'},
 {'PULocationID': '163', 'DOLocationID': '141'},
 {'PULocationID': '48', 'DOLocationID': '48'},
 {'PULocationID': '230', 'DOLocationID': '140'},
 {'PULocationID': '162', 'DOLocationID': '100'},
 {'PULocationID': '230', 'DOLocationID': '17'},
 {'PULocationID': '140', 'DOLocationID': '17'},
 {'PULocationID': '164', 'DOLocationID': '107'},
 {'PULocationID': '224', 'DOLocationID': '229'},
 {'PULocationID': '263', 'DOLocationID': '263'},
 {'PULocationID': '100', 'DOLocationID': '231'},
 {'PULocationID': '263', 'DOLocationID': '50'},
 {'PULocationID': '48', 'DOLocationID': '158'},
 {'PULocationID': '229', 'DOLocationID': '237'},
 {'PULocationID': '162', 'DOLocationID': '213'},
 {'PULocationID': '100', 'DOLocationID': '230'},
 {'PULocationID': '74', 'DOLocationID': '182'},
 {'PULocationID': '24', 'DOLocationID': '48'},
 {'PULocationID': '234', 'DOLocationID': '238'},
 {'PULocationID': '236', 'DOLocationID': '262'},
 {'PULocationID': '100', 'DOLocationID': '48'},
 {'PULocationID': '75', 'DOLocationID': '145'},
 {'PULocationID': '161', 'DOLocationID': '262'},
 {'PULocationID': '262', 'DOLocationID': '233'},
 {'PULocationID': '233', 'DOLocationID': '233'},
 {'PULocationID': '170', 'DOLocationID': '168'},
 {'PULocationID': '237', 'DOLocationID': '142'},
 {'PULocationID': '162', 'DOLocationID': '242'},
 {'PULocationID': '107', 'DOLocationID': '262'},
 {'PULocationID': '262', 'DOLocationID': '263'},
 {'PULocationID': '236', 'DOLocationID': '233'},
 {'PULocationID': '107', 'DOLocationID': '238'},
 {'PULocationID': '239', 'DOLocationID': '48'},

In [63]:
df_fevrier[categorical] = df_fevrier[categorical].astype(str)
dict_fevrier = df_fevrier[categorical].to_dict(orient='records')
dict_fevrier

[{'PULocationID': '141', 'DOLocationID': '226'},
 {'PULocationID': '43', 'DOLocationID': '263'},
 {'PULocationID': '114', 'DOLocationID': '263'},
 {'PULocationID': '236', 'DOLocationID': '229'},
 {'PULocationID': '229', 'DOLocationID': '140'},
 {'PULocationID': '238', 'DOLocationID': '75'},
 {'PULocationID': '132', 'DOLocationID': '200'},
 {'PULocationID': '249', 'DOLocationID': '181'},
 {'PULocationID': '79', 'DOLocationID': '246'},
 {'PULocationID': '75', 'DOLocationID': '74'},
 {'PULocationID': '74', 'DOLocationID': '24'},
 {'PULocationID': '90', 'DOLocationID': '229'},
 {'PULocationID': '75', 'DOLocationID': '88'},
 {'PULocationID': '132', 'DOLocationID': '122'},
 {'PULocationID': '170', 'DOLocationID': '48'},
 {'PULocationID': '142', 'DOLocationID': '90'},
 {'PULocationID': '68', 'DOLocationID': '249'},
 {'PULocationID': '79', 'DOLocationID': '256'},
 {'PULocationID': '79', 'DOLocationID': '256'},
 {'PULocationID': '148', 'DOLocationID': '79'},
 {'PULocationID': '100', 'DOLocationID': '263'},
 {'PULocationID': '132', 'DOLocationID': '39'},
 {'PULocationID': '229', 'DOLocationID': '229'},
 {'PULocationID': '90', 'DOLocationID': '50'},
 {'PULocationID': '246', 'DOLocationID': '238'},
 {'PULocationID': '143', 'DOLocationID': '48'},
 {'PULocationID': '132', 'DOLocationID': '262'},
 {'PULocationID': '132', 'DOLocationID': '188'},
 {'PULocationID': '107', 'DOLocationID': '141'},
 {'PULocationID': '186', 'DOLocationID': '230'},
 {'PULocationID': '48', 'DOLocationID': '143'},
 {'PULocationID': '186', 'DOLocationID': '237'},
 {'PULocationID': '236', 'DOLocationID': '170'},
 {'PULocationID': '132', 'DOLocationID': '241'},
 {'PULocationID': '229', 'DOLocationID': '236'},
 {'PULocationID': '244', 'DOLocationID': '116'},
 {'PULocationID': '79', 'DOLocationID': '260'},
 {'PULocationID': '260', 'DOLocationID': '223'},
 {'PULocationID': '249', 'DOLocationID': '144'},
 {'PULocationID': '186', 'DOLocationID': '151'},
 {'PULocationID': '80', 'DOLocationID': '61'},
 {'PULocationID': '132', 'DOLocationID': '89'},
 {'PULocationID': '140', 'DOLocationID': '151'},
 {'PULocationID': '132', 'DOLocationID': '66'},
 {'PULocationID': '90', 'DOLocationID': '68'},
 {'PULocationID': '186', 'DOLocationID': '37'},
 {'PULocationID': '262', 'DOLocationID': '263'},
 {'PULocationID': '211', 'DOLocationID': '79'},
 {'PULocationID': '237', 'DOLocationID': '141'},
 {'PULocationID': '79', 'DOLocationID': '236'},
 {'PULocationID': '132', 'DOLocationID': '102'},
 {'PULocationID': '230', 'DOLocationID': '48'},
 {'PULocationID': '48', 'DOLocationID': '87'},
 {'PULocationID': '132', 'DOLocationID': '222'},
 {'PULocationID': '132', 'DOLocationID': '225'},
 {'PULocationID': '161', 'DOLocationID': '36'},
 {'PULocationID': '142', 'DOLocationID': '151'},
 {'PULocationID': '151', 'DOLocationID': '229'},
 {'PULocationID': '186', 'DOLocationID': '230'},
 {'PULocationID': '132', 'DOLocationID': '205'},
 {'PULocationID': '162', 'DOLocationID': '107'},
 {'PULocationID': '137', 'DOLocationID': '74'},
 {'PULocationID': '263', 'DOLocationID': '234'},
 {'PULocationID': '170', 'DOLocationID': '107'},
 {'PULocationID': '132', 'DOLocationID': '186'},
 {'PULocationID': '74', 'DOLocationID': '75'},
 {'PULocationID': '186', 'DOLocationID': '107'},
 {'PULocationID': '263', 'DOLocationID': '68'},
 {'PULocationID': '186', 'DOLocationID': '164'},
 {'PULocationID': '68', 'DOLocationID': '246'},
 {'PULocationID': '132', 'DOLocationID': '205'},
 {'PULocationID': '138', 'DOLocationID': '17'},
 {'PULocationID': '158', 'DOLocationID': '100'},
 {'PULocationID': '68', 'DOLocationID': '68'},
 {'PULocationID': '186', 'DOLocationID': '48'},
 {'PULocationID': '68', 'DOLocationID': '50'},
 {'PULocationID': '48', 'DOLocationID': '4'},
 {'PULocationID': '224', 'DOLocationID': '4'},
 {'PULocationID': '239', 'DOLocationID': '198'},
 {'PULocationID': '264', 'DOLocationID': '264'},
 {'PULocationID': '186', 'DOLocationID': '90'},
 {'PULocationID': '186', 'DOLocationID': '142'},
 {'PULocationID': '146', 'DOLocationID': '179'},
 {'PULocationID': '132', 'DOLocationID': '95'},
 {'PULocationID': '132', 'DOLocationID': '89'},
 {'PULocationID': '75', 'DOLocationID': '74'},
 {'PULocationID': '107', 'DOLocationID': '234'},
 {'PULocationID': '234', 'DOLocationID': '4'},
 {'PULocationID': '68', 'DOLocationID': '259'},
 {'PULocationID': '142', 'DOLocationID': '127'},
 {'PULocationID': '186', 'DOLocationID': '137'},
 {'PULocationID': '141', 'DOLocationID': '75'},
 {'PULocationID': '141', 'DOLocationID': '263'},
 {'PULocationID': '264', 'DOLocationID': '264'},
 {'PULocationID': '146', 'DOLocationID': '193'},
 {'PULocationID': '233', 'DOLocationID': '164'},
 {'PULocationID': '230', 'DOLocationID': '48'},
 {'PULocationID': '48', 'DOLocationID': '48'},
 {'PULocationID': '48', 'DOLocationID': '142'},
 {'PULocationID': '48', 'DOLocationID': '230'},
 {'PULocationID': '90', 'DOLocationID': '229'},
 {'PULocationID': '163', 'DOLocationID': '236'},
 {'PULocationID': '170', 'DOLocationID': '14'},
 {'PULocationID': '132', 'DOLocationID': '185'},
 {'PULocationID': '79', 'DOLocationID': '75'},
 {'PULocationID': '132', 'DOLocationID': '203'},
 {'PULocationID': '137', 'DOLocationID': '80'},
 {'PULocationID': '256', 'DOLocationID': '28'},
 {'PULocationID': '137', 'DOLocationID': '100'},
 {'PULocationID': '48', 'DOLocationID': '112'},
 {'PULocationID': '112', 'DOLocationID': '80'},
 {'PULocationID': '236', 'DOLocationID': '97'},
 {'PULocationID': '186', 'DOLocationID': '37'},
 {'PULocationID': '190', 'DOLocationID': '181'},
 {'PULocationID': '137', 'DOLocationID': '42'},
 {'PULocationID': '137', 'DOLocationID': '164'},
 {'PULocationID': '224', 'DOLocationID': '137'},
 {'PULocationID': '186', 'DOLocationID': '42'},
 {'PULocationID': '75', 'DOLocationID': '42'},
 {'PULocationID': '164', 'DOLocationID': '234'},
 {'PULocationID': '186', 'DOLocationID': '163'},
 {'PULocationID': '132', 'DOLocationID': '142'},
 {'PULocationID': '169', 'DOLocationID': '41'},
 {'PULocationID': '230', 'DOLocationID': '113'},
 {'PULocationID': '132', 'DOLocationID': '174'},
 {'PULocationID': '236', 'DOLocationID': '262'},
 {'PULocationID': '263', 'DOLocationID': '107'},
 {'PULocationID': '132', 'DOLocationID': '90'},
 {'PULocationID': '132', 'DOLocationID': '223'},
 {'PULocationID': '152', 'DOLocationID': '249'},
 {'PULocationID': '132', 'DOLocationID': '140'},
 {'PULocationID': '230', 'DOLocationID': '79'},
 {'PULocationID': '230', 'DOLocationID': '50'},
 {'PULocationID': '239', 'DOLocationID': '263'},
 {'PULocationID': '137', 'DOLocationID': '79'},
 {'PULocationID': '166', 'DOLocationID': '74'},
 {'PULocationID': '238', 'DOLocationID': '142'},
 {'PULocationID': '239', 'DOLocationID': '238'},
 {'PULocationID': '107', 'DOLocationID': '232'},
 {'PULocationID': '186', 'DOLocationID': '230'},
 {'PULocationID': '68', 'DOLocationID': '48'},
 {'PULocationID': '229', 'DOLocationID': '129'},
 {'PULocationID': '186', 'DOLocationID': '81'},
 {'PULocationID': '88', 'DOLocationID': '232'},
 {'PULocationID': '90', 'DOLocationID': '75'},
 {'PULocationID': '148', 'DOLocationID': '40'},
 {'PULocationID': '162', 'DOLocationID': '161'},
 {'PULocationID': '162', 'DOLocationID': '121'},
 {'PULocationID': '88', 'DOLocationID': '189'},
 {'PULocationID': '148', 'DOLocationID': '234'},
 {'PULocationID': '68', 'DOLocationID': '42'},
 {'PULocationID': '239', 'DOLocationID': '50'},
 {'PULocationID': '186', 'DOLocationID': '68'},
 {'PULocationID': '236', 'DOLocationID': '75'},
 {'PULocationID': '236', 'DOLocationID': '113'},
 {'PULocationID': '107', 'DOLocationID': '164'},
 {'PULocationID': '24', 'DOLocationID': '151'},
 {'PULocationID': '186', 'DOLocationID': '236'},
 {'PULocationID': '162', 'DOLocationID': '48'},
 {'PULocationID': '68', 'DOLocationID': '170'},
 {'PULocationID': '148', 'DOLocationID': '48'},
 {'PULocationID': '186', 'DOLocationID': '238'},
 {'PULocationID': '132', 'DOLocationID': '39'},
 {'PULocationID': '186', 'DOLocationID': '144'},
 {'PULocationID': '163', 'DOLocationID': '142'},
 {'PULocationID': '132', 'DOLocationID': '216'},
 {'PULocationID': '138', 'DOLocationID': '151'},
 {'PULocationID': '186', 'DOLocationID': '4'},
 {'PULocationID': '79', 'DOLocationID': '161'},
 {'PULocationID': '132', 'DOLocationID': '29'},
 {'PULocationID': '141', 'DOLocationID': '74'},
 {'PULocationID': '186', 'DOLocationID': '50'},
 {'PULocationID': '132', 'DOLocationID': '76'},
 {'PULocationID': '68', 'DOLocationID': '79'},
 {'PULocationID': '186', 'DOLocationID': '50'},
 {'PULocationID': '132', 'DOLocationID': '138'},
 {'PULocationID': '48', 'DOLocationID': '50'},
 {'PULocationID': '132', 'DOLocationID': '256'},
 {'PULocationID': '132', 'DOLocationID': '39'},
 {'PULocationID': '263', 'DOLocationID': '61'},
 {'PULocationID': '48', 'DOLocationID': '74'},
 {'PULocationID': '132', 'DOLocationID': '238'},
 {'PULocationID': '229', 'DOLocationID': '50'},
 {'PULocationID': '162', 'DOLocationID': '141'},
 {'PULocationID': '142', 'DOLocationID': '143'},
 {'PULocationID': '79', 'DOLocationID': '229'},
 {'PULocationID': '74', 'DOLocationID': '205'},
 {'PULocationID': '263', 'DOLocationID': '229'},
 {'PULocationID': '143', 'DOLocationID': '186'},
 {'PULocationID': '143', 'DOLocationID': '229'},
 {'PULocationID': '132', 'DOLocationID': '265'},
 {'PULocationID': '141', 'DOLocationID': '87'},
 {'PULocationID': '211', 'DOLocationID': '234'},
 {'PULocationID': '132', 'DOLocationID': '248'},
 {'PULocationID': '132', 'DOLocationID': '265'},
 {'PULocationID': '141', 'DOLocationID': '114'},
 {'PULocationID': '137', 'DOLocationID': '164'},
 {'PULocationID': '137', 'DOLocationID': '164'},
 {'PULocationID': '143', 'DOLocationID': '41'},
 {'PULocationID': '166', 'DOLocationID': '116'},
 {'PULocationID': '132', 'DOLocationID': '76'},
 {'PULocationID': '162', 'DOLocationID': '148'},
 {'PULocationID': '114', 'DOLocationID': '148'},
 {'PULocationID': '162', 'DOLocationID': '70'},
 {'PULocationID': '70', 'DOLocationID': '70'},
 {'PULocationID': '186', 'DOLocationID': '79'},
 {'PULocationID': '68', 'DOLocationID': '68'},
 {'PULocationID': '141', 'DOLocationID': '168'},
 {'PULocationID': '161', 'DOLocationID': '238'},
 {'PULocationID': '48', 'DOLocationID': '68'},
 {'PULocationID': '68', 'DOLocationID': '48'},
 {'PULocationID': '140', 'DOLocationID': '234'},
 {'PULocationID': '231', 'DOLocationID': '113'},
 {'PULocationID': '186', 'DOLocationID': '79'},
 {'PULocationID': '132', 'DOLocationID': '216'},
 {'PULocationID': '238', 'DOLocationID': '186'},
 {'PULocationID': '238', 'DOLocationID': '75'},
 {'PULocationID': '132', 'DOLocationID': '131'},
 {'PULocationID': '264', 'DOLocationID': '264'},
 {'PULocationID': '263', 'DOLocationID': '75'},
 {'PULocationID': '188', 'DOLocationID': '72'},
 {'PULocationID': '125', 'DOLocationID': '141'},
 {'PULocationID': '114', 'DOLocationID': '225'},
 {'PULocationID': '116', 'DOLocationID': '41'},
 {'PULocationID': '230', 'DOLocationID': '143'},
 {'PULocationID': '100', 'DOLocationID': '42'},
 {'PULocationID': '132', 'DOLocationID': '163'},
 {'PULocationID': '148', 'DOLocationID': '100'},
 {'PULocationID': '75', 'DOLocationID': '41'},
 {'PULocationID': '243', 'DOLocationID': '256'},
 {'PULocationID': '264', 'DOLocationID': '264'},
 {'PULocationID': '239', 'DOLocationID': '41'},
 {'PULocationID': '142', 'DOLocationID': '143'},
 {'PULocationID': '143', 'DOLocationID': '143'},
 {'PULocationID': '142', 'DOLocationID': '152'},
 {'PULocationID': '48', 'DOLocationID': '50'},
 {'PULocationID': '48', 'DOLocationID': '129'},
 {'PULocationID': '107', 'DOLocationID': '141'},
 {'PULocationID': '144', 'DOLocationID': '4'},
 {'PULocationID': '141', 'DOLocationID': '229'},
 {'PULocationID': '90', 'DOLocationID': '148'},
 {'PULocationID': '48', 'DOLocationID': '116'},
 {'PULocationID': '90', 'DOLocationID': '90'},
 {'PULocationID': '79', 'DOLocationID': '4'},
 {'PULocationID': '137', 'DOLocationID': '79'},
 {'PULocationID': '141', 'DOLocationID': '141'},
 {'PULocationID': '137', 'DOLocationID': '4'},
 {'PULocationID': '262', 'DOLocationID': '94'},
 {'PULocationID': '236', 'DOLocationID': '162'},
 {'PULocationID': '237', 'DOLocationID': '168'},
 {'PULocationID': '132', 'DOLocationID': '193'},
 {'PULocationID': '162', 'DOLocationID': '25'},
 {'PULocationID': '186', 'DOLocationID': '41'},
 {'PULocationID': '7', 'DOLocationID': '173'},
 {'PULocationID': '186', 'DOLocationID': '161'},
 {'PULocationID': '230', 'DOLocationID': '234'},
 {'PULocationID': '162', 'DOLocationID': '56'},
 {'PULocationID': '186', 'DOLocationID': '35'},
 {'PULocationID': '132', 'DOLocationID': '91'},
 {'PULocationID': '75', 'DOLocationID': '263'},
 {'PULocationID': '186', 'DOLocationID': '50'},
 {'PULocationID': '74', 'DOLocationID': '42'},
 {'PULocationID': '186', 'DOLocationID': '142'},
 {'PULocationID': '186', 'DOLocationID': '232'},
 {'PULocationID': '107', 'DOLocationID': '263'},
 {'PULocationID': '132', 'DOLocationID': '31'},
 {'PULocationID': '233', 'DOLocationID': '162'},
 {'PULocationID': '166', 'DOLocationID': '166'},
 {'PULocationID': '48', 'DOLocationID': '226'},
 {'PULocationID': '162', 'DOLocationID': '198'},
 {'PULocationID': '230', 'DOLocationID': '52'},
 {'PULocationID': '230', 'DOLocationID': '52'},
 {'PULocationID': '132', 'DOLocationID': '130'},
 {'PULocationID': '48', 'DOLocationID': '229'},
 {'PULocationID': '162', 'DOLocationID': '229'},
 {'PULocationID': '239', 'DOLocationID': '230'},
 {'PULocationID': '239', 'DOLocationID': '230'},
 {'PULocationID': '100', 'DOLocationID': '4'},
 {'PULocationID': '141', 'DOLocationID': '75'},
 {'PULocationID': '75', 'DOLocationID': '75'},
 {'PULocationID': '229', 'DOLocationID': '244'},
 {'PULocationID': '246', 'DOLocationID': '164'},
 {'PULocationID': '161', 'DOLocationID': '100'},
 {'PULocationID': '132', 'DOLocationID': '63'},
 {'PULocationID': '137', 'DOLocationID': '224'},
 {'PULocationID': '166', 'DOLocationID': '166'},
 {'PULocationID': '79', 'DOLocationID': '68'},
 {'PULocationID': '79', 'DOLocationID': '68'},
 {'PULocationID': '229', 'DOLocationID': '148'},
 {'PULocationID': '68', 'DOLocationID': '107'},
 {'PULocationID': '239', 'DOLocationID': '83'},
 {'PULocationID': '234', 'DOLocationID': '4'},
 {'PULocationID': '132', 'DOLocationID': '69'},
 {'PULocationID': '234', 'DOLocationID': '198'},
 {'PULocationID': '107', 'DOLocationID': '170'},
 {'PULocationID': '186', 'DOLocationID': '246'},
 {'PULocationID': '144', 'DOLocationID': '231'},
 {'PULocationID': '186', 'DOLocationID': '75'},
 {'PULocationID': '170', 'DOLocationID': '7'},
 {'PULocationID': '75', 'DOLocationID': '75'},
 {'PULocationID': '114', 'DOLocationID': '232'},
 {'PULocationID': '42', 'DOLocationID': '194'},
 {'PULocationID': '141', 'DOLocationID': '234'},
 {'PULocationID': '75', 'DOLocationID': '41'},
 {'PULocationID': '186', 'DOLocationID': '17'},
 {'PULocationID': '45', 'DOLocationID': '181'},
 {'PULocationID': '233', 'DOLocationID': '75'},
 {'PULocationID': '162', 'DOLocationID': '48'},
 {'PULocationID': '116', 'DOLocationID': '116'},
 {'PULocationID': '142', 'DOLocationID': '48'},
 {'PULocationID': '230', 'DOLocationID': '48'},
 {'PULocationID': '186', 'DOLocationID': '261'},
 {'PULocationID': '229', 'DOLocationID': '137'},
 {'PULocationID': '234', 'DOLocationID': '68'},
 {'PULocationID': '90', 'DOLocationID': '164'},
 {'PULocationID': '164', 'DOLocationID': '68'},
 {'PULocationID': '137', 'DOLocationID': '246'},
 {'PULocationID': '168', 'DOLocationID': '48'},
 {'PULocationID': '142', 'DOLocationID': '239'},
 {'PULocationID': '146', 'DOLocationID': '234'},
 {'PULocationID': '79', 'DOLocationID': '171'},
 {'PULocationID': '68', 'DOLocationID': '158'},
 {'PULocationID': '263', 'DOLocationID': '262'},
 {'PULocationID': '42', 'DOLocationID': '127'},
 {'PULocationID': '48', 'DOLocationID': '68'},
 {'PULocationID': '186', 'DOLocationID': '234'},
 {'PULocationID': '186', 'DOLocationID': '250'},
 {'PULocationID': '186', 'DOLocationID': '234'},
 {'PULocationID': '186', 'DOLocationID': '7'},
 {'PULocationID': '230', 'DOLocationID': '186'},
 {'PULocationID': '230', 'DOLocationID': '186'},
 {'PULocationID': '68', 'DOLocationID': '42'},
 {'PULocationID': '141', 'DOLocationID': '98'},
 {'PULocationID': '186', 'DOLocationID': '48'},
 {'PULocationID': '186', 'DOLocationID': '161'},
 {'PULocationID': '186', 'DOLocationID': '166'},
 {'PULocationID': '132', 'DOLocationID': '69'},
 {'PULocationID': '170', 'DOLocationID': '246'},
 {'PULocationID': '100', 'DOLocationID': '230'},
 {'PULocationID': '142', 'DOLocationID': '263'},
 {'PULocationID': '238', 'DOLocationID': '230'},
 {'PULocationID': '151', 'DOLocationID': '42'},
 {'PULocationID': '186', 'DOLocationID': '238'},
 {'PULocationID': '48', 'DOLocationID': '138'},
 {'PULocationID': '186', 'DOLocationID': '75'},
 {'PULocationID': '230', 'DOLocationID': '226'},
 {'PULocationID': '141', 'DOLocationID': '171'},
 {'PULocationID': '230', 'DOLocationID': '42'},
 {'PULocationID': '68', 'DOLocationID': '100'},
 {'PULocationID': '41', 'DOLocationID': '42'},
 {'PULocationID': '68', 'DOLocationID': '74'},
 {'PULocationID': '74', 'DOLocationID': '75'},
 {'PULocationID': '233', 'DOLocationID': '114'},
 {'PULocationID': '90', 'DOLocationID': '129'},
 {'PULocationID': '181', 'DOLocationID': '143'},
 {'PULocationID': '143', 'DOLocationID': '143'},
 {'PULocationID': '186', 'DOLocationID': '75'},
 {'PULocationID': '186', 'DOLocationID': '230'},
 {'PULocationID': '107', 'DOLocationID': '63'},
 {'PULocationID': '164', 'DOLocationID': '194'},
 {'PULocationID': '77', 'DOLocationID': '71'},
 {'PULocationID': '79', 'DOLocationID': '68'},
 {'PULocationID': '68', 'DOLocationID': '61'},
 {'PULocationID': '166', 'DOLocationID': '186'},
 {'PULocationID': '265', 'DOLocationID': '265'},
 {'PULocationID': '42', 'DOLocationID': '74'},
 {'PULocationID': '75', 'DOLocationID': '151'},
 {'PULocationID': '142', 'DOLocationID': '186'},
 {'PULocationID': '249', 'DOLocationID': '88'},
 {'PULocationID': '229', 'DOLocationID': '233'},
 {'PULocationID': '233', 'DOLocationID': '74'},
 {'PULocationID': '79', 'DOLocationID': '232'},
 {'PULocationID': '74', 'DOLocationID': '41'},
 {'PULocationID': '186', 'DOLocationID': '186'},
 {'PULocationID': '141', 'DOLocationID': '140'},
 {'PULocationID': '237', 'DOLocationID': '141'},
 {'PULocationID': '68', 'DOLocationID': '42'},
 {'PULocationID': '263', 'DOLocationID': '75'},
 {'PULocationID': '263', 'DOLocationID': '87'},
 {'PULocationID': '141', 'DOLocationID': '236'},
 {'PULocationID': '164', 'DOLocationID': '41'},
 {'PULocationID': '38', 'DOLocationID': '137'},
 {'PULocationID': '132', 'DOLocationID': '209'},
 {'PULocationID': '137', 'DOLocationID': '169'},
 {'PULocationID': '244', 'DOLocationID': '238'},
 {'PULocationID': '50', 'DOLocationID': '75'},
 {'PULocationID': '75', 'DOLocationID': '263'},
 {'PULocationID': '249', 'DOLocationID': '144'},
 {'PULocationID': '249', 'DOLocationID': '148'},
 {'PULocationID': '79', 'DOLocationID': '217'},
 {'PULocationID': '256', 'DOLocationID': '229'},
 {'PULocationID': '100', 'DOLocationID': '90'},
 {'PULocationID': '137', 'DOLocationID': '182'},
 {'PULocationID': '263', 'DOLocationID': '113'},
 {'PULocationID': '79', 'DOLocationID': '234'},
 {'PULocationID': '24', 'DOLocationID': '140'},
 {'PULocationID': '237', 'DOLocationID': '143'},
 {'PULocationID': '146', 'DOLocationID': '144'},
 {'PULocationID': '230', 'DOLocationID': '90'},
 {'PULocationID': '68', 'DOLocationID': '65'},
 {'PULocationID': '68', 'DOLocationID': '87'},
 {'PULocationID': '75', 'DOLocationID': '114'},
 {'PULocationID': '90', 'DOLocationID': '48'},
 {'PULocationID': '90', 'DOLocationID': '100'},
 {'PULocationID': '74', 'DOLocationID': '254'},
 {'PULocationID': '233', 'DOLocationID': '170'},
 {'PULocationID': '186', 'DOLocationID': '166'},
 {'PULocationID': '137', 'DOLocationID': '56'},
 {'PULocationID': '262', 'DOLocationID': '74'},
 {'PULocationID': '100', 'DOLocationID': '90'},
 {'PULocationID': '234', 'DOLocationID': '79'},
 {'PULocationID': '143', 'DOLocationID': '162'},
 {'PULocationID': '48', 'DOLocationID': '239'},

In [64]:
dv_janvier = DictVectorizer()
dv_fevrier = DictVectorizer()

In [71]:
Xj_train = dv_janvier.fit_transform(dict_janvier)

In [77]:
# question 4
Xj_train.shape[1]

518

In [79]:
target = 'duration'
y_train = df_janvier[target].values

lr = LinearRegression()
lr.fit(Xj_train, y_train)
y_pred = lr.predict(Xj_train)

In [80]:
# question 5
rmse = root_mean_squared_error(y_train, y_pred)
rmse

6.845620262707853

In [82]:
Xf_val = dv_fevrier.fit_transform(dict_fevrier)

y_val = df_fevrier[target].values
yf_pred = lr.predict(Xf_val)

In [83]:
# question 6
rmse_fev = root_mean_squared_error(y_val, yf_pred)
rmse_fev

7.737378613912077